development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zeroxerodev
  pool: 5
  username: zrdevel
  password: dup4

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zeroxerodev
  pool: 5
  username: zrdevel
  password: dup4

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: zeroxerotest
  pool: 5
  username: zrtest
  password: dup4
